version: 2
executorType: docker
containerInfo:
    - image: levlaz/elasticsearch-docker-ci:5.1.1
    - image: rabbitmq:3.5.4
stages:
  build:
    workDir: /root
    steps:
      - type: shell
        name: Test ElasticSearch
        command: curl -I --retry 10 --retry-delay 10 -XGET 'localhost:5672'
