version: 2
executorType: docker
containerInfo:
    - image: elasticsearch:5.1
stages:
  build:
    workDir: /root
    steps:
      - type: shell
        name: Test ElasticSearch
        command: |
          ss -plntu
          curl http://127.0.0.1:9200/
          ps auxfww
          sleep 35
          curl http://127.0.0.1:9200/

