version: 2
executorType: docker
containerInfo:
    - image: elasticsearch:5.1
stages:
  build:
    workDir: /root
    steps:
      - type: shell
        name: Test ElasticSearch
        command: |
          ss -plntu
          curl -I -XGET 'localhost:9200/_count?pretty' -d '{"query": {"match_all": {}}}'
          ps auxfww
      - type: shell
        name: Is it running
        command: curl -I -XGET 'localhost:9200/_count?pretty' -d '{"query": {"match_all": {}}}'
