version: 2
executorType: docker
containerInfo:
    - image: elasticsearch:5.1
stages:
  build:
    workDir: /root
    steps:
      - type: shell
        name: Test ElasticSearch
        command: |
          ss -plntu
          curl -i -XGET 'localhost:9200/'
          ps auxfww
          sleep 35
          curl -i -XGET 'localhost:9200/'

