version: 2
executorType: docker
containerInfo:
    - image: elasticsearch:5.1
stages:
  build:
    workDir: /home/ubuntu/project
    steps:
      - type: checkout
      - type: shell
        name: Test ElasticSearch
        command: |
          ss -plntu
          netstat -pltnu
          curl http://127.0.0.1:9200/
          ps auxfww
