version: 2
executorType: docker
containerInfo:
    - image: levlaz/elasticsearch-docker-ci:5.1.1
    - image: rabbitmq:3.5.4
stages:
  build:
    workDir: /root
    steps:
      - type: shell
        name: Test ElasticSearch
        command: |
          curl -I -XGET 'localhost:8080'
          wget --tries 10 --timeout=15 --read-timeout=20 --waitretry=30 --retry-connrefused 'localhost:8080'
