version: 2
executorType: docker
containerInfo:
    - image: elasticsearch:5.1
stages:
  build:
    workDir: /root
    steps:
      - type: shell
        name: Test ElasticSearch
        command: |
          ss -plntu
          curl -i -XGET 'localhost:9200/'
          ps auxfww
      - type: shell
        name: Is it running yet?
        command: \
          sleep 35 && curl -XGET 'localhost:9200/_count?pretty' -d '{"query": {"match_all": {}}}'
