version: 2
executorType: docker
containerInfo:
    - image: levlaz/elasticsearch-docker-ci:5.1.1
stages:
  build:
    workDir: /root
    steps:
      - type: shell
        name: Test ElasticSearch
        command: |
          curl -I -XGET 'localhost:9200/_count?pretty' -d '{"query": {"match_all": {}}}'
          ps auxfww
          wget --tries 180 --timeout=15 --read-timeout=20 --waitretry=1 --retry-connrefused 'localhost:9200/_count?pretty' -d '{"query": {"match_all": {}}}'
          ss -plntu
